[package]
authors = ["baptistecdr <baptistecdr@users.noreply.github.com>"]
build = false
categories = ["api-bindings"]
description = "A Rust wrapper for RARBG TorrentAPI"
exclude = [".idea", "src/main.rs"]
keywords = ["rarbg_api", "rarbg", "rarbg_wrapper", "rarbg_client", "torrent_api"]
license = "MIT"
name = "rarbg_api"
publish = ["crates-io"]
repository = "https://github.com/baptistecdr/rarbg_api"
version = "0.5.3"

[dependencies]
chrono = {version = "0.4.19", features = ["serde"]}
reqwest = {version = "0.10.10", features = ["blocking", "json"]}
serde = {version = "1.0.123", features = ["derive"]}
serde_json = "1.0.62"
uuid = {version = "0.8.2", features = ["v4"]}
