[package]
authors = ["baptistecdr <baptistecdr@users.noreply.github.com>"]
build = false
categories = ["api-bindings"]
description = "A Rust wrapper for RARBG TorrentAPI"
exclude = [".*", "renovate.json", "*.magnet"]
keywords = ["rarbg_api", "rarbg", "rarbg_wrapper", "rarbg_client", "torrent_api"]
license = "MIT"
name = "rarbg_api"
publish = ["crates-io"]
repository = "https://github.com/baptistecdr/rarbg_api"
version = "1.0.29"
edition = "2018"

[dependencies]
chrono = { version = "0.4.22", features = ["serde"] }
reqwest = { version = "0.11.12", features = ["blocking", "json"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
uuid = { version = "1.1.2", features = ["v4"] }
tokio = { version = "1.21.2", features = ["full"] }
tokio-test = { version = "0.4.2" }
