name: Release Major

on: workflow_dispatch

jobs:
  release-major:
    name: Release Major
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
      - name: Setup Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4
        with:
          go-version: '1.20.3'
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # tag=v1
        name: Setup Rust
        with:
          toolchain: stable
      - name: Install dependencies
        run: |
          sudo apt-get install -y jq
          go install github.com/sclevine/yj/v5@v5.1.0
          cargo install cargo-edit
      - name: Set major version
        id: major_version
        run: |
          cargo set-version --workspace --bump major
          MAJOR_VERSION=$(cat Cargo.toml | yj -tj | jq -r .package.version)
          TOKIO_VERSION=$(cat Cargo.toml | yj -tj | jq -r .dependencies.tokio.version)
          sed -i "s/^rarbg_api = \".*\"$/rarbg_api = \"$MAJOR_VERSION\"/g" README.md
          sed -i "s/^tokio = { version = \".*\",/tokio = { version = \"$TOKIO_VERSION\",/g" README.md
          echo "MAJOR_VERSION=$MAJOR_VERSION" >> $GITHUB_OUTPUT
      - name: Commit, push and create tag
        uses: EndBug/add-and-commit@1bad3abcf0d6ec49a5857d124b0bfb52dc7bb081 # v9
        with:
          fetch: true
          default_author: github_actions
          message: Release v${{ steps.major_version.outputs.MAJOR_VERSION }}
          pathspec_error_handling: exitImmediately
          push: true
          tag: v${{ steps.major_version.outputs.MAJOR_VERSION }}
      - name: Set next dev version
        id: dev_version
        run: |
          cargo set-version --workspace --bump rc
          DEV_VERSION=$(cat Cargo.toml | yj -tj | jq -r .package.version)
          sed -i "s/^rarbg_api = \".*\"$/rarbg_api = \"$DEV_VERSION\"/g" README.md
          echo "DEV_VERSION=$DEV_VERSION" >> $GITHUB_OUTPUT
      - name: Commit and push
        uses: EndBug/add-and-commit@1bad3abcf0d6ec49a5857d124b0bfb52dc7bb081 # v9
        with:
          fetch: true
          default_author: github_actions
          message: Set next dev version to v${{ steps.dev_version.outputs.DEV_VERSION }}
          pathspec_error_handling: exitImmediately
          push: true
