name: Rust

on:
  push:
    branches:
      - '**'
    pull_request:
      - '**'
    tags-ignore:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        name: Clone Repository
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # tag=v1
        name: Get Rust Toolchain
        with:
          toolchain: stable
      - name: Check Code Style
        run: cargo fmt --verbose
      - name: Run Linter
        run: cargo clippy --verbose
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
