name: Rust Release

on:
  push:
    tags:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3
        name: Clone Repository
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # tag=v1
        name: Setup Rust
        with:
          toolchain: stable
      - uses: katyo/publish-crates@e83e72af4fbc5013e7fc275ad55828623e854858 # v2
        name: Publish to Crates.io
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
